---

- hosts: all
  become: true
  tasks:

    - name: Update Repository and Install apache and php packages
      apt:
        update_cache: yes
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Update Repository and Install apache and php packages
      dnf:
        update_cache: yes
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "OracleLinux"

