---

- hosts: all
  become: true
  tasks:

    - name: Update Repository Index; Remove apache2 package; Add php support for Apache
      apt:
        update_cache: yes
        name: 
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"
    - name: Update Repository Index; Remove apache2 package; Add php support for Apache
      dnf:
        update_cache: yes
        name: 
          - httpd
          - php
        state: absent
      when: ansible_distribution == "OracleLinux"
   

